---
title: "LearnWoCrash"
author: "Benjamin Evans"
date: "26/01/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

data = read.csv("DataTable.csv")
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)

```

# Kernel Safety Tests

Firstly, we run random tests to ensure that the kernels are safe and that they do work.

```{r}
kernel_gen = data %>%
  filter(eval_name=="KernelGen")%>%
  select(kernel_mode, map_name, avg_times)%>%
  pivot_wider(names_from = kernel_mode, values_from = avg_times)
  
# tab = table(kernel_gen$map_name, c)

kable(kernel_gen)
```




# Tests

# Comparision

## Performance Table



```{r}
kernel_gen = data %>%
  filter(EvalName=="PerfTable")%>%
  select(vehicle, crashes,  avg_times, success_rate)

kable(kernel_gen)
```


## Repeatability


```{r}
repeatability = data %>%
  filter(EvalName=="Repeatability") %>%
  filter(avg_times<1000)%>%
  select(map_name, avg_times, success_rate, vehicle)%>%
  group_by(vehicle)%>%
  mutate(mean_time=mean(success_rate))%>%
  ggplot(aes(x=vehicle, y=success_rate, group=vehicle))+
  geom_boxplot()+
  geom_point()+
  geom_point(aes(y=mean_time), shape='x', size=10)
repeatability
```
```{r}
repeatability = data %>%
  filter(EvalName=="Repeatability") %>%
  filter(avg_times<1000)%>%
  select(map_name, avg_times, success_rate, vehicle)%>%
  group_by(vehicle)%>%
  mutate(mean_time=mean(avg_times))%>%
  ggplot(aes(x=vehicle, y=avg_times, group=vehicle))+
  geom_boxplot()+
  geom_point()+
  geom_point(aes(y=mean_time), shape='x', size=10)
repeatability
```

```{r}
rep_tab = data %>%
  filter(EvalName=="Repeatability") %>%
  filter(avg_times<1000)%>%
  select(map_name, avg_times, success_rate, vehicle, kernel_reward)%>%
  group_by(kernel_reward)%>%
  mutate(mean_time=mean(avg_times))

repeatability
```

## Rewards
```{r}
reward = data %>%
  filter(EvalName=="Reward") %>%
  filter(avg_times<1000)%>%
  select(reward, kernel_reward, rk, avg_times, success_rate)


kable(reward)
```

