mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158

max_v: 4
min_v: 2
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2

# Vehicle parameters
n_beams: 20
range_finder_scale: 5
h_size: 100

# Simulator parameters
time_step: 0.1
update_steps: 1
max_steps: 1000
end_distance: 1.2

vehicle_path: "Data/PaperVehicles/"
# map_name: "porto"
map_name: "columbia_small"
# map_name: "f1_aut_wide"

kernel_path: "Data/Kernels/"
dynamics_path: "Data/Dynamics/"
kernel_mode: "disc"
# kernel_mode: "viab"
n_phi: 41

nq_steer: 5
nq_velocity: 3
phi_range: 6.28
n_dx: 40
lookahead_time_step: 0.2

mag_reward: 0
constant_reward: 1

r1: 0.08
r2: 0.001
rk: 0.04

vehicle: KernelSSS

train_n: 10000
test_n: 20

traj_path: "Data/Trajectories/"


