mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158

max_v: 7
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2

# Vehicle parameters
n_beams: 20
range_finder_scale: 5
h_size: 100

# Simulator parameters
time_step: 0.1
update_steps: 1
max_steps: 5000
end_distance: 1.2

vehicle_path: "Data/PaperVehicles/"
map_name: "porto"
# map_name: "columbia_small"
# map_name: "f1_aut_wide"

r1: 0.08
r2: 0.002
rk: 0

vehicle: Baseline

# Reward
reward: 'cthRef'

train_n: 20000
test_n: 100
