min_v: 2
max_v: 4
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2

mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158
n_beams: 20

# Simulator parameters
time_step: 0.1
update_steps: 1
max_steps: 5000
end_distance: 1.5

map_name: "porto"
# map_name: "columbia_small"
# map_name: "f1_aut_wide"

kernel_path: "Data/PaperKernels/"
dynamics_path: "Data/Dynamics/"
# kernel_mode: "disc"
kernel_mode: "viab"
n_phi: 41
nq_steer: 5
nq_velocity: 3
phi_range: 6.28
discrim_block: 1
discrim_phi: 0
kernel_time_step: 0.1
lookahead_time_step: 0.2
n_dx: 40


vehicle_path: "Data/PaperVehicles/"

EvalName: "KernelGen"
