run_name: RewardTest

base_config_name: "PaperRewards"

runs:
  # - run: 1
  #   name: "StdReward"
  #   rk: 0
  - run: 2
    name: "NegativeBias04"
    rk: 0.04
  # - run: 3
  #   name: "NegativeBias1"
  #   rk: 0.1
