mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158

max_v: 7
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2

# Vehicle parameters
n_beams: 20

# Simulator parameters
time_step: 0.1
update_steps: 1
max_steps: 5000
end_distance: 1.5
# end_distance: 3

vehicle_path: "PaperData/Vehicles/"
# map_name: "torino"
# map_name: "berlin"
map_name: "porto"
# map_name: "race_track"

kernel_path: "PaperData/Kernels/"
# kernel_mode: "disc"
kernel_mode: "viab"
n_phi: 41
n_modes: 5
phi_range: 6.28
discrim_block: 1
discrim_phi: 0
kernel_time_step: 0.1
lookahead_time_step: 0.2
n_dx: 80

vehicle: constant

test_n: 1
EvalName: "Safety"

constant_value: 0
test_number: 0

