mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158

max_v: 4
min_v: 2
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2

# Vehicle parameters
n_beams: 20
range_finder_scale: 5
h_size: 100

# Simulator parameters
time_step: 0.1
update_steps: 1
max_steps: 5000
end_distance: 1.2
# end_distance: 0.7
# end_distance: 3

vehicle_path: "Data/Vehicles/"
# map_name: "torino"
# map_name: "berlin"
# map_name: "porto"
map_name: "columbia_small"
# map_name: "f1_aut_wide"
# map_name: "circle"
# map_name: "torino_redraw_small"

kernel_path: "Data/Kernels/"
dynamics_path: "Data/Dynamics/"
kernel_mode: "disc"
# kernel_mode: "viab"
n_phi: 41
# n_modes: 5

nq_steer: 5
nq_velocity: 3
phi_range: 6.28
discrim_block: 1
discrim_phi: 0
kernel_time_step: 0.1
lookahead_time_step: 0.2
n_dx: 40

kernel_reward: "Magnitude"
sss_reward_scale: 0.5

r1: 0.08
r2: 0.004

vehicle: reactive

# Reward
reward: 'cthRef'

train_n: 10000
test_n: 10

lookahead: 1.2
v_gain: 0.6
traj_path: "Data/Trajectories/"
